// content/activewear/sweatshirts.ts
// Crewneck Sweatshirts PLP, rebuilt from the owner's final content brief
// (2026-09-23): 16 draft SKUs (CAP-SWT-01 to 16, numbered to match the
// source research doc, not renumbered), 8 men's and 8 women's, crewneck
// only (the earlier half-zip, quarter-zip and mock-neck cards and FAQ are
// gone). Same locked PLP template and data shape as every other category.
//
// Gendering: four style names exist on both sides (Oversized Brushed Fleece,
// Regular-Fit Brushed Fleece, Technical Performance, French Terry). Those
// cards carry the gendered "Men's ..." / "Women's ..." title with no
// "Custom" prefix, and their slugs take a "-mens" / "-womens" suffix (the
// brief gave identical slugs for each pair, which would collide on one
// URL; same suffix pattern as T-Shirts and Tank Tops). Every other style
// keeps the un-gendered "Custom ..." title and its given slug.
//
// Every style is "draft" with no PDP content, so each card is a
// non-clickable tile, with no route, no sitemap entry and no ItemList
// entry until its own PDP is built and published.
import type { Category } from "./types";
import { faqGetStarted } from "./pdpShared";

export const sweatshirts: Category = {
  slug: "sweatshirts",
  group: "Activewear",
  menuLabel: "Sweatshirts",
  // Entity FAQ parts (categoryEntityFaq(), ./pdpShared.ts). No
  // `entityFabrics`: the brief's entity answer names styles only, so the
  // fabric clause drops out and the sentence reads exactly as given.
  manufacturerNoun: "Sweatshirt",
  productNounPlural: "crewneck sweatshirts",
  entityExampleStyles:
    "oversized, regular-fit, technical performance, and French terry styles for men, and oversized, cropped, regular-fit, and technical performance styles for women",
  h1: "Custom Sweatshirt Manufacturer",
  metaTitle: "Custom Sweatshirt Manufacturer",
  // 156 chars, owner-measured and confirmed as rendered.
  metaDescription:
    "Custom sweatshirt manufacturer, private label crewnecks in French terry or brushed fleece, low MOQ from 50 pieces, full customization, DDP to 20+ countries.",
  trustBullets: ["MOQ from 50 pieces", "Samples in 10 to 14 days", "OEM, ODM & Private Label", "DDP to 20+ countries"],
  gridSubline: "Every style, made to your brand spec",
  gridSublineMobile: "Every style is available in custom fabrics & colors",
  showGenderFilter: true,
  fabricEyebrow: "FABRIC OPTIONS",
  // Same sitewide H2 wording and "\n" line break as every category.
  fabricHeading: "The fabrics behind the\nbig brands",
  fabricOptions: [
    {
      fabric: "French terry (loopback, unbrushed)",
      bestFor: "Structured, breathable crewnecks, screen print and DTG",
      performance: "Smooth face, looped interior, breathes, resists pilling, holds its shape",
    },
    {
      fabric: "Brushed fleece",
      bestFor: "Warmer, plusher crewneck feel, embroidery",
      performance: "Napped soft interior, warmer at the same weight, a fuller hand for dimensional embroidery",
    },
    {
      fabric: "Cotton-poly blend (commonly 80/20)",
      bestFor: "Retail, promo, collegiate and corporate programs",
      performance: "Balances cost, shrink control and embroidery stability",
    },
    {
      fabric: "100% cotton, compacted",
      bestFor: "Premium retail and streetwear",
      performance: "Softer hand, compacted for shrink control",
    },
    {
      fabric: "Tri-blend fleece (poly / combed cotton / rayon)",
      bestFor: "Premium, soft vintage hand",
      performance: "Exceptionally soft, lighter drape",
    },
    {
      fabric: "Recycled fiber blend",
      bestFor: "Sustainable lines",
      performance: "Comparable to standard cotton-poly, eco-positioning",
    },
  ],
  weightTiers: [
    {
      tier: "Lightweight",
      gsm: "250 to 300 GSM",
      bestFor: "Layering, spring and fall, promo and uniform programs",
    },
    {
      tier: "Midweight",
      gsm: "300 to 350 GSM",
      bestFor: "The most common crewneck band, everyday retail and team programs",
    },
    {
      tier: "Heavyweight",
      gsm: "400 to 475+ GSM",
      bestFor: "Premium and streetwear, a durable, substantial feel",
    },
  ],
  fabricNote: [
    { text: "Crewnecks run about a step lighter than hoodies (no hood or pocket to add fabric and construction), so the same feel lands at a lower GSM. The ribbed collar, cuffs, and waistband carry " },
    { text: "Spandex", bold: true },
    { text: " for recovery and a flat, non-curling collar. Garment-dye is available. Swatches before every bulk run, and we can source or match a " },
    { text: "specific fabric or GSM", bold: true },
    { text: " from your reference." },
  ],
  fabricPills: [
    "French terry",
    "Brushed fleece",
    "Cotton-poly blend",
    "Compacted cotton",
    "Tri-blend fleece",
    "Recycled blend",
  ],
  qualityHeading: "A flat collar, the weight you approve",
  qualitySubline: "We confirm the collar, GSM, and shrinkage on your sample before a single bulk piece is cut",
  qualityPoints: [
    "Ribbed collar lies flat and holds its recovery, no curling",
    "Spandex-reinforced collar, cuffs, and hem, confirmed content",
    "GSM held consistent, batch to batch, not just on the sample",
    "Shrinkage tested after wash, targeted under 5%, brushed fleece checked for pilling",
    "Every run inspected to AQL 2.5, third-party inspection welcome",
  ],
  coverageEyebrow: "CUSTOMIZATION",
  coverageHeading: "From custom fabric to packaging design",
  coverageItems: [
    { title: "Fabric", body: "French terry, brushed fleece, cotton-poly, tri-blend, and recycled fiber blends" },
    { title: "Weight and fit", body: "250 to 475+ GSM, regular, oversized, or cropped" },
    {
      title: "Collar and construction",
      body: "Crew collar with optional V-stitch sweat-guard, set-in, raglan, or drop-shoulder sleeve",
    },
    { title: "Color and print", body: "Custom colors with Pantone matching, screen, DTG, DTF, embroidery, puff, patches" },
    { title: "Labels", body: "Woven, printed, or tear-away labels, hangtags" },
    { title: "Packaging", body: "Polybags, boxes, retail-ready to your spec" },
  ],
  // Same sitewide FAQ heading. The entity question (FAQ 1) is built by
  // categoryEntityFaq() from the entity fields above and prepended at
  // render time; the last entry is the shared, locked get-started Q&A.
  faqHeading: "Top questions from B2B buyers",
  faqs: [
    {
      q: "What is your MOQ for custom sweatshirts?",
      a: "From 50 pieces per style, and you can mix sizes freely within a colorway. Scales to full bulk.",
    },
    {
      q: "What is the difference between a crewneck sweatshirt and a hoodie?",
      a: "A crewneck is the same fleece body and sleeve as a hoodie, without the hood, drawcord, and kangaroo pocket, keeping the round ribbed collar. It uses less fabric and simpler construction, so it is often the more cost-efficient first SKU. Many brands start with a midweight crewneck in core colors, then add hoodies in the best sellers.",
    },
    {
      q: "What fabric weights (GSM) do you offer?",
      a: "Lightweight 250 to 300 GSM, midweight 300 to 350 GSM (the standard band), and heavyweight 400 to 475+ GSM. Crewnecks run about a step lighter than hoodies at the same feel.",
    },
    {
      q: "How do you keep the collar from curling?",
      a: "The ribbed crew collar is fully exposed, so we build Spandex into the collar rib and test its recovery, so it lies flat and does not curl after washing. A V-stitch sweat-guard is available as an optional heritage detail.",
    },
    {
      q: "Can you match a specific GSM or a reference sweatshirt?",
      a: "Yes. Send a reference or tech pack and we match the fabric, GSM, and hand-feel, then confirm on your sample.",
    },
    {
      q: "What print and branding methods can you do?",
      a: "Screen print and DTG on French terry, embroidery and puff on brushed fleece and heavier weights, plus DTF and patches. With no hood or front pocket, the chest and full back are open zones for large prints.",
    },
    {
      q: "Will my sweatshirts shrink or pill?",
      a: "We test shrinkage after wash, targeting under 5 percent, and check brushed fleece for pilling, before bulk.",
    },
    {
      q: "What can I customize?",
      a: "Everything from fabric to packaging: fabric, weight, fit, collar construction, sleeve construction, cuffs, color and finish (including garment-dye), print and embroidery, your logos, labels, hangtags, and packaging.",
    },
    {
      q: "Do you offer OEM, ODM, and private label sweatshirts?",
      a: "Yes, all three, made under your brand.",
    },
    {
      q: "How are sweatshirts sized?",
      a: "Alpha XS to 5XL. Unisex, men's, and women's fits use the same size range with a different cut, unisex is boxier, women's is tapered.",
    },
    {
      q: "How long do samples and bulk take?",
      a: "Samples in 10 to 14 days. Bulk lead time depends on quantity and customization, confirmed on your quote.",
    },
    {
      q: "Do you ship to my country?",
      a: "Yes, DDP to 20+ countries, including the US, UK, EU, Canada, and Australia, with GSP+ 0% EU duty.",
    },
    {
      q: "Will my designs stay protected?",
      a: "Yes. We sign an NDA before any tech pack.",
    },
    faqGetStarted,
  ],
  ctaReferenceNoun: "sweatshirt",
  styleCards: [
    {
      status: "draft",
      slug: "oversized-brushed-fleece-mens",
      cardTitle: "Men's Oversized Brushed Fleece Crewneck Sweatshirt",
      cardSubline: "Roomy relaxed fit, midweight brushed fleece",
      image: "",
      imageAlt: "Men's oversized brushed fleece crewneck sweatshirt, roomy relaxed fit, midweight brushed fleece",
      href: "/capriowear/activewear/sweatshirts/oversized-brushed-fleece-mens",
      gender: "Men",
      sku: "CAP-SWT-01",
    },
    {
      status: "draft",
      slug: "oversized-french-terry",
      cardTitle: "Custom Oversized French Terry Crewneck Sweatshirt",
      cardSubline: "Extra-roomy fit, heavyweight French terry, drawcord hem",
      image: "",
      imageAlt: "Custom oversized French terry crewneck sweatshirt, extra-roomy fit, heavyweight French terry, drawcord hem",
      href: "/capriowear/activewear/sweatshirts/oversized-french-terry",
      gender: "Men",
      sku: "CAP-SWT-02",
    },
    {
      status: "draft",
      slug: "regular-fit-brushed-fleece-mens",
      cardTitle: "Men's Regular-Fit Brushed Fleece Crewneck Sweatshirt",
      cardSubline: "Standard fit, cotton-blend fleece, brushed inside",
      image: "",
      imageAlt: "Men's regular-fit brushed fleece crewneck sweatshirt, standard fit, cotton-blend fleece, brushed inside",
      href: "/capriowear/activewear/sweatshirts/regular-fit-brushed-fleece-mens",
      gender: "Men",
      sku: "CAP-SWT-05",
      pdpTitle: "Men's Regular-Fit Brushed Fleece Crewneck",
      pdpHeading: "Men's Regular-Fit Brushed Fleece Crewneck Sweatshirt Manufacturer",
      pdpDescription:
        "Men's standard-fit crewneck sweatshirt in cotton-blend brushed fleece, custom and private label, with a flat, spandex-reinforced collar, made to your brand in Sialkot, Pakistan.",
      images: [
        { alt: "Regular-fit brushed fleece crewneck sweatshirt, front view, men's" },
        { alt: "Regular-fit brushed fleece crewneck sweatshirt, back view, men's" },
        { alt: "Regular-fit brushed fleece crewneck sweatshirt, collar detail, men's" },
        { alt: "Regular-fit brushed fleece crewneck sweatshirt, brushed fleece interior, men's" },
        { alt: "Regular-fit brushed fleece crewneck sweatshirt, worn on model, men's" },
        { alt: "Regular-fit brushed fleece crewneck sweatshirt, flat lay, men's" },
      ],
      pdpMetaTitle: "Men's Regular-Fit Brushed Fleece Crewneck Sweatshirt Manufacturer",
      pdpMetaDescription:
        "Men's regular-fit brushed fleece crewneck sweatshirt manufacturer, private label, cotton-blend fleece, flat spandex collar, low MOQ, DDP to 20+ countries.",
      material: "Cotton-blend brushed fleece",
      pdpFabricPills: ["Brushed Fleece", "Cotton-Poly Blend", "French Terry", "Tri-Blend Fleece"],
      pdpCustomizationPills: ["Custom fabric", "Custom color & print", "Your fit", "Your branding", "Custom labels", "Custom packaging"],
      faqs: [
        {
          q: "How does the regular fit compare to your oversized crewneck?",
          a: "This is a true-to-size, standard fit through the body and sleeve, not the roomy oversized block. If you want the boxier oversized silhouette instead, our Oversized Brushed Fleece Crewneck uses the same fabric family on a roomier pattern.",
        },
        {
          q: "Is the fleece brushed on the inside, outside, or both?",
          a: "Brushed on the inside face only, for warmth against the skin, with a smooth cotton-blend outer face that takes print and embroidery cleanly.",
        },
      ],
      relatedStyleTags: [
        { label: "Men's Oversized Brushed Fleece Crewneck", slug: "oversized-brushed-fleece-mens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Custom Oversized French Terry Crewneck", slug: "oversized-french-terry", href: "/capriowear/activewear/sweatshirts" },
        { label: "Men's Technical Performance Crewneck", slug: "technical-performance-mens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Custom Oversized Cropped Fleece Crewneck", slug: "oversized-cropped", href: "/capriowear/activewear/sweatshirts" },
        { label: "See All", href: "/capriowear/activewear/sweatshirts" },
      ],
      specifications: [
        { label: "Style", value: "Men's standard, true-to-size crewneck sweatshirt, no hood, no zip (base type)" },
        { label: "Fabric", value: "Cotton-blend brushed fleece" },
        { label: "Weight", value: "Pending, confirmed on your sample." },
        { label: "Fit", value: "Standard, true-to-size through the body and sleeve" },
        { label: "Collar", value: "Round ribbed crew, spandex-reinforced to lie flat, optional V-stitch sweat-guard" },
        { label: "Cuffs and hem", value: "Ribbed knit with spandex for recovery" },
        { label: "Sleeve", value: "Set-in sleeve" },
        { label: "Construction", value: "Cut-and-sew, side-seam or tubular body to your spec" },
        { label: "Branding", value: "Screen, DTG, DTF, embroidery, puff, patches, custom labels and packaging" },
      ],
      specificationsImage: { alt: "Regular-fit brushed fleece crewneck sweatshirt, construction detail, men's" },
      pdpQualitySubline: "We confirm it all on your sample before a single bulk piece is cut.",
      pdpQualityPoints: [
        "Ribbed collar lies flat and holds its recovery, no curling",
        "GSM held consistent, batch to batch",
        "Shrinkage tested after wash, targeted under 5%, brushed fleece checked for pilling",
        "Cuffs and hem hold their recovery",
        "Every run inspected to AQL 2.5, third-party inspection welcome",
      ],
      pdpCustomizationSteps: {
        eyebrow: "HOW WE CUSTOMIZE",
        heading: "Your brand, applied\nin-house, no outsourcing",
        mobileHeading: "Your brand, applied in-\nhouse, no outsourcing",
        steps: [
          { title: "Print and artwork", body: "Screen, DTG, DTF, puff", image: { src: "/factory-test/inside-factory-2.jpg", alt: "Print and artwork" } },
          { title: "Branding", body: "Embroidery, patches, heat transfer", image: { src: "/factory-test/inside-factory-3.jpg", alt: "Branding" } },
          { title: "Fabric and weight", body: "Cotton-blend brushed fleece, any GSM, sourced or matched to your reference", image: { src: "/factory-test/inside-factory-1.jpg", alt: "Fabric and weight" } },
          { title: "Build", body: "Collar, sleeve construction, V-stitch, cuffs to your spec", image: { src: "/factory-test/inside-factory-4.jpg", alt: "Build" } },
          { title: "Finish", body: "Standard or garment-dye", image: { src: "/factory-test/inside-factory-5.jpg", alt: "Finish" } },
          { title: "Trims and packaging", body: "Woven or tear-away labels, hangtags, retail-ready packaging", image: { src: "/factory-test/inside-factory-1.jpg", alt: "Trims and packaging" } },
        ],
      },
    },
    {
      status: "draft",
      slug: "technical-performance-mens",
      cardTitle: "Men's Technical Performance Crewneck Sweatshirt",
      cardSubline: "Double-knit fabric, sweat-wicking performance finish",
      image: "",
      imageAlt: "Men's technical performance crewneck sweatshirt, double-knit fabric, sweat-wicking performance finish",
      href: "/capriowear/activewear/sweatshirts/technical-performance-mens",
      gender: "Men",
      sku: "CAP-SWT-06",
      pdpTitle: "Men's Technical Performance Crewneck",
      pdpHeading: "Men's Technical Performance Crewneck Sweatshirt Manufacturer",
      pdpDescription:
        "Men's performance crewneck sweatshirt in a double-knit, moisture-wicking fabric, custom and private label, with a flat, spandex-reinforced collar, made to your brand in Sialkot, Pakistan.",
      images: [
        { alt: "Technical performance crewneck sweatshirt, front view, men's" },
        { alt: "Technical performance crewneck sweatshirt, back view, men's" },
        { alt: "Technical performance crewneck sweatshirt, collar detail, men's" },
        { alt: "Technical performance crewneck sweatshirt, double-knit fabric close-up, men's" },
        { alt: "Technical performance crewneck sweatshirt, worn on model, men's" },
        { alt: "Technical performance crewneck sweatshirt, flat lay, men's" },
      ],
      pdpMetaTitle: "Men's Technical Performance Crewneck Sweatshirt Manufacturer",
      pdpMetaDescription:
        "Men's technical performance crewneck sweatshirt manufacturer, private label, moisture-wicking double-knit fabric, low MOQ from 50 pieces, DDP to 20+ countries.",
      material: "Double-knit performance fabric with a moisture-wicking finish",
      pdpFabricPills: ["Performance Double-Knit", "French Terry", "Brushed Fleece", "Cotton-Poly Blend"],
      pdpCustomizationPills: ["Custom fabric", "Custom color & print", "Your fit", "Your branding", "Custom labels", "Custom packaging"],
      faqs: [
        {
          q: "What makes this crewneck \"performance\" rather than standard fleece?",
          a: "It's built in a double-knit, moisture-wicking fabric instead of brushed fleece or terry, so it manages sweat and dries faster while keeping the same crewneck silhouette. It suits training and transitional wear better than a lounge-weight fleece.",
        },
        {
          q: "Can you match a specific performance fabric or finish?",
          a: "Yes. Send a reference or tech pack and we source or match the knit structure and moisture-wicking finish, confirmed on your sample.",
        },
      ],
      relatedStyleTags: [
        { label: "Men's Oversized Brushed Fleece Crewneck", slug: "oversized-brushed-fleece-mens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Men's Regular-Fit Brushed Fleece Crewneck", slug: "regular-fit-brushed-fleece-mens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Custom Oversized French Terry Crewneck", slug: "oversized-french-terry", href: "/capriowear/activewear/sweatshirts" },
        { label: "Custom Oversized Cropped Fleece Crewneck", slug: "oversized-cropped", href: "/capriowear/activewear/sweatshirts" },
        { label: "See All", href: "/capriowear/activewear/sweatshirts" },
      ],
      specifications: [
        { label: "Style", value: "Men's standard-fit crewneck sweatshirt, no hood, no zip, performance fabric (base type)" },
        { label: "Fabric", value: "Double-knit performance fabric, moisture-wicking finish" },
        { label: "Weight", value: "Pending, confirmed on your sample." },
        { label: "Fit", value: "Standard, true-to-size through the body and sleeve" },
        { label: "Collar", value: "Round ribbed crew, spandex-reinforced to lie flat" },
        { label: "Cuffs and hem", value: "Ribbed knit with spandex for recovery" },
        { label: "Sleeve", value: "Set-in sleeve" },
        { label: "Construction", value: "Cut-and-sew, side-seam or tubular body to your spec" },
        { label: "Branding", value: "Screen, DTG, DTF, embroidery, puff, patches, custom labels and packaging" },
      ],
      specificationsImage: { alt: "Technical performance crewneck sweatshirt, construction detail, men's" },
      pdpQualitySubline: "We confirm it all on your sample before a single bulk piece is cut.",
      pdpQualityPoints: [
        "Ribbed collar lies flat and holds its recovery, no curling",
        "GSM held consistent, batch to batch",
        "Moisture-wicking finish tested for wicking performance and wash durability",
        "Shrinkage tested after wash, targeted under 5%",
        "Every run inspected to AQL 2.5, third-party inspection welcome",
      ],
      pdpCustomizationSteps: {
        eyebrow: "HOW WE CUSTOMIZE",
        heading: "Your brand, applied\nin-house, no outsourcing",
        mobileHeading: "Your brand, applied in-\nhouse, no outsourcing",
        steps: [
          { title: "Print and artwork", body: "Screen, DTG, DTF, puff", image: { src: "/factory-test/inside-factory-2.jpg", alt: "Print and artwork" } },
          { title: "Branding", body: "Embroidery, patches, heat transfer", image: { src: "/factory-test/inside-factory-3.jpg", alt: "Branding" } },
          { title: "Fabric and weight", body: "Double-knit performance fabric, any GSM, sourced or matched to your reference, moisture-wicking finish applied to your spec", image: { src: "/factory-test/inside-factory-1.jpg", alt: "Fabric and weight" } },
          { title: "Build", body: "Collar, sleeve construction, cuffs to your spec", image: { src: "/factory-test/inside-factory-4.jpg", alt: "Build" } },
          { title: "Finish", body: "Standard or garment-dye", image: { src: "/factory-test/inside-factory-5.jpg", alt: "Finish" } },
          { title: "Trims and packaging", body: "Woven or tear-away labels, hangtags, retail-ready packaging", image: { src: "/factory-test/inside-factory-1.jpg", alt: "Trims and packaging" } },
        ],
      },
    },
    {
      status: "draft",
      slug: "french-terry-mens",
      cardTitle: "Men's French Terry Crewneck Sweatshirt",
      cardSubline: "Smooth outside, warm brushed inside, stretch recovery",
      image: "",
      imageAlt: "Men's French terry crewneck sweatshirt, smooth outside, warm brushed inside, stretch recovery",
      href: "/capriowear/activewear/sweatshirts/french-terry-mens",
      gender: "Men",
      sku: "CAP-SWT-07",
    },
    {
      status: "draft",
      slug: "premium-tech-fleece",
      cardTitle: "Custom Premium Tech Fleece Loose-Fit Crewneck Sweatshirt",
      cardSubline: "Loose fit, premium technical fleece, vent detailing",
      image: "",
      imageAlt: "Custom premium tech fleece loose-fit crewneck sweatshirt, loose fit, premium technical fleece, vent detailing",
      href: "/capriowear/activewear/sweatshirts/premium-tech-fleece",
      gender: "Men",
      sku: "CAP-SWT-08",
    },
    {
      status: "draft",
      slug: "reverse-french-terry",
      cardTitle: "Custom Reverse French Terry Crewneck Sweatshirt",
      cardSubline: "Soft fleece feel without brushed-fleece heat",
      image: "",
      imageAlt: "Custom reverse French terry crewneck sweatshirt, soft fleece feel without brushed-fleece heat",
      href: "/capriowear/activewear/sweatshirts/reverse-french-terry",
      gender: "Men",
      sku: "CAP-SWT-09",
    },
    {
      status: "draft",
      slug: "vintage-terry",
      cardTitle: "Custom Vintage-Wash Terry Crewneck Sweatshirt",
      cardSubline: "Heavyweight cotton terry, cracked vintage-wash finish",
      image: "",
      imageAlt: "Custom vintage-wash terry crewneck sweatshirt, heavyweight cotton terry, cracked vintage-wash finish",
      href: "/capriowear/activewear/sweatshirts/vintage-terry",
      gender: "Men",
      sku: "CAP-SWT-10",
    },
    {
      status: "draft",
      slug: "oversized-brushed-fleece-womens",
      cardTitle: "Women's Oversized Brushed Fleece Crewneck Sweatshirt",
      cardSubline: "Roomy relaxed fit, midweight brushed fleece",
      image: "",
      imageAlt: "Women's oversized brushed fleece crewneck sweatshirt, roomy relaxed fit, midweight brushed fleece",
      href: "/capriowear/activewear/sweatshirts/oversized-brushed-fleece-womens",
      gender: "Women",
      sku: "CAP-SWT-03",
    },
    {
      status: "draft",
      slug: "oversized-cropped",
      cardTitle: "Custom Oversized Cropped Fleece Crewneck Sweatshirt",
      cardSubline: "Oversized fit, shortened cropped body length",
      image: "",
      imageAlt: "Custom oversized cropped fleece crewneck sweatshirt, oversized fit, shortened cropped body length",
      href: "/capriowear/activewear/sweatshirts/oversized-cropped",
      gender: "Women",
      sku: "CAP-SWT-04",
      pdpTitle: "Oversized Cropped Fleece Crewneck",
      pdpHeading: "Custom Oversized Cropped Fleece Crewneck Sweatshirt Manufacturer",
      pdpDescription:
        "Women's oversized crewneck sweatshirt with a cropped body length, custom and private label, in midweight fleece with a spandex-reinforced collar, made to your brand in Sialkot, Pakistan.",
      images: [
        { alt: "Oversized cropped fleece crewneck sweatshirt, front view" },
        { alt: "Oversized cropped fleece crewneck sweatshirt, cropped hem detail" },
        { alt: "Oversized cropped fleece crewneck sweatshirt, back view" },
        { alt: "Oversized cropped fleece crewneck sweatshirt, collar detail" },
        { alt: "Oversized cropped fleece crewneck sweatshirt, worn on model" },
        { alt: "Oversized cropped fleece crewneck sweatshirt, flat lay" },
      ],
      pdpMetaTitle: "Custom Oversized Cropped Fleece Crewneck Sweatshirt Manufacturer",
      pdpMetaDescription:
        "Custom oversized cropped fleece crewneck sweatshirt manufacturer, private label, cropped body length, midweight fleece, low MOQ, DDP to 20+ countries.",
      material: "Midweight cotton-poly blend fleece",
      pdpFabricPills: ["Brushed Fleece", "French Terry", "Cotton-Poly Blend", "Tri-Blend Fleece"],
      pdpCustomizationPills: ["Custom fabric", "Custom color & print", "Your fit", "Your branding", "Custom labels", "Custom packaging"],
      faqs: [
        {
          q: "How cropped is the body length on this style?",
          a: "Cropped to sit around the high hip, shorter than our standard oversized crewneck but still full through the body and sleeve for the oversized silhouette. We confirm the exact body length on your sample, matched to your spec.",
        },
        {
          q: "Can I adjust the crop length or go back to a full-length body?",
          a: "Yes. Crop length is built to your tech pack, and we can lengthen it back to a standard oversized body if you want both versions cut from the same pattern block.",
        },
      ],
      relatedStyleTags: [
        { label: "Women's Oversized Brushed Fleece Crewneck", slug: "oversized-brushed-fleece-womens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Women's Regular-Fit Brushed Fleece Crewneck", slug: "regular-fit-brushed-fleece-womens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Women's Technical Performance Crewneck", slug: "technical-performance-womens", href: "/capriowear/activewear/sweatshirts" },
        { label: "Men's Oversized Brushed Fleece Crewneck", slug: "oversized-brushed-fleece-mens", href: "/capriowear/activewear/sweatshirts" },
        { label: "See All", href: "/capriowear/activewear/sweatshirts" },
      ],
      specifications: [
        { label: "Style", value: "Women's oversized crewneck sweatshirt, cropped body length, no hood, no zip (base type)" },
        { label: "Fabric", value: "Midweight fleece (cotton-poly blend)" },
        { label: "Weight", value: "Pending, confirmed on your sample." },
        { label: "Fit", value: "Oversized through the body and sleeve, cropped body length" },
        { label: "Collar", value: "Round ribbed crew, spandex-reinforced to lie flat, optional V-stitch sweat-guard" },
        { label: "Cuffs and hem", value: "Ribbed knit with spandex for recovery" },
        { label: "Sleeve", value: "Set-in sleeve" },
        { label: "Construction", value: "Cut-and-sew, side-seam or tubular body to your spec" },
        { label: "Branding", value: "Screen, DTG, DTF, embroidery, puff, patches, custom labels and packaging" },
      ],
      specificationsImage: { alt: "Oversized cropped fleece crewneck sweatshirt, construction detail" },
      pdpQualitySubline: "We confirm it all on your sample before a single bulk piece is cut.",
      pdpQualityPoints: [
        "Ribbed collar lies flat and holds its recovery, no curling",
        "GSM held consistent, batch to batch",
        "Shrinkage tested after wash, targeted under 5%, fleece checked for pilling",
        "Cropped hem and cuffs hold their shape wash after wash",
        "Every run inspected to AQL 2.5, third-party inspection welcome",
      ],
      pdpCustomizationSteps: {
        eyebrow: "HOW WE CUSTOMIZE",
        heading: "Your brand, applied\nin-house, no outsourcing",
        mobileHeading: "Your brand, applied in-\nhouse, no outsourcing",
        steps: [
          { title: "Print and artwork", body: "Screen, DTG, DTF, puff", image: { src: "/factory-test/inside-factory-2.jpg", alt: "Print and artwork" } },
          { title: "Branding", body: "Embroidery, patches, heat transfer", image: { src: "/factory-test/inside-factory-3.jpg", alt: "Branding" } },
          { title: "Fabric and weight", body: "Midweight fleece, any GSM, sourced or matched to your reference", image: { src: "/factory-test/inside-factory-1.jpg", alt: "Fabric and weight" } },
          { title: "Build", body: "Collar, sleeve construction, V-stitch, cropped body length to your spec", image: { src: "/factory-test/inside-factory-4.jpg", alt: "Build" } },
          { title: "Finish", body: "Standard or garment-dye", image: { src: "/factory-test/inside-factory-5.jpg", alt: "Finish" } },
          { title: "Trims and packaging", body: "Woven or tear-away labels, hangtags, retail-ready packaging", image: { src: "/factory-test/inside-factory-1.jpg", alt: "Trims and packaging" } },
        ],
      },
    },
    {
      status: "draft",
      slug: "regular-fit-brushed-fleece-womens",
      cardTitle: "Women's Regular-Fit Brushed Fleece Crewneck Sweatshirt",
      cardSubline: "Standard fit, medium-weight fleece",
      image: "",
      imageAlt: "Women's regular-fit brushed fleece crewneck sweatshirt, standard fit, medium-weight fleece",
      href: "/capriowear/activewear/sweatshirts/regular-fit-brushed-fleece-womens",
      gender: "Women",
      sku: "CAP-SWT-11",
    },
    {
      status: "draft",
      slug: "technical-performance-womens",
      cardTitle: "Women's Technical Performance Crewneck Sweatshirt",
      cardSubline: "Sport-finish fabric, sweat-wicking performance crew",
      image: "",
      imageAlt: "Women's technical performance crewneck sweatshirt, sport-finish fabric, sweat-wicking performance crew",
      href: "/capriowear/activewear/sweatshirts/technical-performance-womens",
      gender: "Women",
      sku: "CAP-SWT-12",
    },
    {
      status: "draft",
      slug: "french-terry-womens",
      cardTitle: "Women's French Terry Crewneck Sweatshirt",
      cardSubline: "Lightweight French terry, quick-dry finish",
      image: "",
      imageAlt: "Women's French terry crewneck sweatshirt, lightweight French terry, quick-dry finish",
      href: "/capriowear/activewear/sweatshirts/french-terry-womens",
      gender: "Women",
      sku: "CAP-SWT-13",
    },
    {
      status: "draft",
      slug: "cropped-mod-fit",
      cardTitle: "Custom Cropped Mod-Fit Crewneck Sweatshirt",
      cardSubline: "Mod-crop, loose-fit proportion, heavyweight fleece",
      image: "",
      imageAlt: "Custom cropped mod-fit crewneck sweatshirt, mod-crop, loose-fit proportion, heavyweight fleece",
      href: "/capriowear/activewear/sweatshirts/cropped-mod-fit",
      gender: "Women",
      sku: "CAP-SWT-14",
    },
    {
      status: "draft",
      slug: "stretch-blend-oversized",
      cardTitle: "Custom Stretch-Blend Oversized Crewneck Sweatshirt",
      cardSubline: "Oversized fit, lightweight stretch fleece with spandex",
      image: "",
      imageAlt: "Custom stretch-blend oversized crewneck sweatshirt, oversized fit, lightweight stretch fleece with spandex",
      href: "/capriowear/activewear/sweatshirts/stretch-blend-oversized",
      gender: "Women",
      sku: "CAP-SWT-15",
    },
    {
      status: "draft",
      slug: "oversized-heavyweight-terry",
      cardTitle: "Custom Oversized Heavyweight Terry Crewneck Sweatshirt",
      cardSubline: "Oversized drop-shoulder fit, heavyweight cotton-blend terry",
      image: "",
      imageAlt: "Custom oversized heavyweight terry crewneck sweatshirt, oversized drop-shoulder fit, heavyweight cotton-blend terry",
      href: "/capriowear/activewear/sweatshirts/oversized-heavyweight-terry",
      gender: "Women",
      sku: "CAP-SWT-16",
    },
  ],
  // "You may also be interested in" (owner rule, 2026-09-23): max 5, same L1 group first
  // (Tops, per activewearMegaMenu), then the closest pairings from other groups.
  relatedLinks: [
    { label: "Hoodies", href: "/capriowear/activewear/hoodies" },
    { label: "Long-Sleeve Tops", href: "/capriowear/activewear/long-sleeve-tops" },
    { label: "T-Shirts", href: "/capriowear/activewear/t-shirts" },
    { label: "Tank Tops", href: "/capriowear/activewear/tank-tops" },
    { label: "Sports Bras", href: "/capriowear/activewear/sports-bras" },
  ],
};
